alias(
    name = "wpimath",
    actual = "@allwpilib//dependencies/cpp/wpimath",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//dependencies/cpp/wpimath:jni",
    visibility = ["//visibility:public"],
)