module(
    name = "bzlmodrio",
    version = "2023.2",
    compatibility_level = 2023,
)

bazel_dep(name = "bzlmodrio-allwpilib", version = "2026.2.1")
bazel_dep(name = "bzlmodrio-ni", version = "2026.1.0")
bazel_dep(name = "bzlmodrio-opencv", version = "2025.4.10.0-3.bcr3")
bazel_dep(name = "bzlmodrio-phoenix", version = "5.36.0")
bazel_dep(name = "bzlmodrio-revlib", version = "2026.0.1")
bazel_dep(name = "rules_bazelrio", version = "0.0.14")
bazel_dep(name = "rules_bzlmodrio_toolchains", version = "2025-1.bcr6")
bazel_dep(name = "rules_checkstyle", version = "10.12.2.bcr1")
bazel_dep(name = "rules_pmd", version = "7.2.0.bcr1")
bazel_dep(name = "rules_spotless", version = "2.40.0.bcr1")
bazel_dep(name = "rules_wpi_styleguide", version = "2025.06.22")
bazel_dep(name = "rules_wpiformat", version = "2025.68")
bazel_dep(name = "bzlmodrio-photonlib", version = "v2026.2.2")
bazel_dep(name = "bzlmodrio-pathplannerlib", version = "2026.1.2")
bazel_dep(name = "bzlmodrio-phoenix6", version = "26.1.1")
bazel_dep(name = "bzlmodrio-choreolib", version = "2026.0.1")
bazel_dep(name = "rules_bzlmodrio_jdk", version = "17.0.12-7.bcr1")
bazel_dep(name = "bzlmodrio-studica", version = "2026.0.0")
