alias(
    name = "wpiutil",
    actual = "@allwpilib//libraries/cpp/wpiutil",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//libraries/cpp/wpiutil:jni",
    visibility = ["//visibility:public"],
)
