local_repository(
    name = "bazelrio",
    path = "..",
)

load("@bazelrio//private/non_bzlmod:download_dependencies.bzl", "download_dependencies")

download_dependencies(
    # allwpilib_version = "local",
    # apriltaglib_version = "local",
    # imgui_version = "local",
    # libssh_version = "local",
    # navx_version = "local",
    # ni_version = "local",
    # opencv_version = "local",
    # phoenix_version = "local",
    # revlib_version = "local",
    # rules_bazelrio_version = "local",
    # rules_toolchains_version = "local",
    # rules_checkstyle_version = "local",
    # rules_pmd_version = "local",
    # rules_spotless_version = "local",
    # rules_wpi_styleguide_version = "local",
    # rules_wpiformat_version = "local",
    # photonlib_version = "local",
    # pathplannerlib_version = "local",
    # phoenix6_version = "local",
)

load("@bazelrio//private/non_bzlmod:setup_dependencies.bzl", "get_java_dependencies", "setup_dependencies")

setup_dependencies()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_artifacts, maven_repositories = get_java_dependencies()

maven_install(
    name = "maven",
    artifacts = maven_artifacts,
    repositories = maven_repositories,
    # maven_install_json = "//build_scripts/bazel/deps:maven_install.json",
)

load("@rules_wpi_styleguide//dependencies:load_rule_dependencies.bzl", "load_styleguide_rule_dependencies")

load_styleguide_rule_dependencies()

load("@rules_wpi_styleguide//dependencies:load_dependencies.bzl", "load_styleguide_dependencies")

load_styleguide_dependencies()

load("@rules_wpi_styleguide//dependencies:load_transitive_dependencies.bzl", "load_styleguide_transitive_dependencies")

load_styleguide_transitive_dependencies()

load("@rules_wpi_styleguide//dependencies:setup_styleguide.bzl", "setup_styleguide")

setup_styleguide()

load("@rules_wpi_styleguide//dependencies:load_pins.bzl", "load_styleguide_pins")

load_styleguide_pins()
