py_binary(
    name = "generate",
    srcs = ["generate.py"],
    deps = [
        # "@allwpilib//generate_allwpilib:get_allwpilib_dependencies",
        "@bzlmodrio-gentool//bazelrio_gentool",
    ],
)
