py_binary(
    name = "generate",
    srcs = ["generate.py"],
    deps = [
        "@bzlmodrio-allwpilib-gentool//:get_allwpilib_dependencies",
        "@bzlmodrio-gentool//bazelrio_gentool",
        "@bzlmodrio-imgui-gentool//:get_imgui_dependencies",
        "@bzlmodrio-libssh-gentool//:get_libssh_dependencies",
        "@bzlmodrio-navx-gentool//:get_navx_dependencies",
        "@bzlmodrio-phoenix-gentool//:get_ctre_dependencies",
        "@bzlmodrio-revlib-gentool//:get_rev_dependencies",
    ],
)
