workspace(name = "rules_bazelrio_gentool")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python, for gentool
http_archive(
    name = "rules_python",
    sha256 = "0a8003b044294d7840ac7d9d73eef05d6ceb682d7516781a4ec62eeb34702578",
    strip_prefix = "rules_python-0.24.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.24.0/rules_python-0.24.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

local_repository(
    name = "bzlmodrio-gentool",
    path = "../../gentool",
)

local_repository(
    name = "bzlmodrio-opencv-gentool",
    path = "../../libraries/bzlmodRio-opencv/generate",
)

local_repository(
    name = "bzlmodrio-ni-gentool",
    path = "../../libraries/bzlmodRio-ni/generate",
)

local_repository(
    name = "bzlmodrio-allwpilib-gentool",
    path = "../../libraries/bzlmodRio-allwpilib/generate",
)

local_repository(
    name = "bzlmodrio-phoenix-gentool",
    path = "../../libraries/bzlmodRio-phoenix/generate",
)

local_repository(
    name = "bzlmodrio-revlib-gentool",
    path = "../../libraries/bzlmodRio-revlib/generate",
)

local_repository(
    name = "bzlmodrio-navx-gentool",
    path = "../../libraries/bzlmodRio-navx/generate",
)

local_repository(
    name = "bzlmodrio-imgui-gentool",
    path = "../../libraries/bzlmodRio-imgui/generate",
)

local_repository(
    name = "bzlmodrio-libssh-gentool",
    path = "../../libraries/bzlmodRio-libssh/generate",
)

local_repository(
    name = "bzlmodrio-apriltaglib-gentool",
    path = "../../libraries/bzlmodRio-apriltaglib/generate",
)

local_repository(
    name = "bzlmodrio-pathplannerlib-gentool",
    path = "../../libraries/bzlmodRio-pathplannerlib/generate",
)

local_repository(
    name = "bzlmodrio-photonlib-gentool",
    path = "../../libraries/bzlmodRio-photonlib/generate",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "bzlmodrio-gentool-pip",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)

load("@bzlmodrio-gentool-pip//:requirements.bzl", "install_deps")

install_deps()
