workspace(name = "rules_bazelrio_gentool")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python, for gentool
http_archive(
    name = "rules_python",
    sha256 = "497ca47374f48c8b067d786b512ac10a276211810f4a580178ee9b9ad139323a",
    strip_prefix = "rules_python-0.16.1",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.16.1.tar.gz",
)

local_repository(
    name = "bzlmodrio-gentool",
    path = "../../gentool",
)

local_repository(
    name = "bzlmodrio-opencv-gentool",
    path = "../../libraries/bzlmodRio-opencv/generate",
)

local_repository(
    name = "bzlmodrio-ni-gentool",
    path = "../../libraries/bzlmodRio-ni/generate",
)

local_repository(
    name = "bzlmodrio-allwpilib-gentool",
    path = "../../libraries/bzlmodRio-allwpilib/generate",
)

local_repository(
    name = "bzlmodrio-phoenix-gentool",
    path = "../../libraries/bzlmodRio-ctre/generate",
)

local_repository(
    name = "bzlmodrio-revlib-gentool",
    path = "../../libraries/bzlmodRio-revlib/generate",
)

local_repository(
    name = "bzlmodrio-navx-gentool",
    path = "../../libraries/bzlmodRio-navx/generate",
)

local_repository(
    name = "bzlmodrio-imgui-gentool",
    path = "../../libraries/bzlmodRio-imgui/generate",
)

local_repository(
    name = "bzlmodrio-libssh-gentool",
    path = "../../libraries/bzlmodRio-libssh/generate",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "bzlmodrio-gentool-pip",
    requirements_lock = "@bzlmodrio-gentool//:requirements_lock.txt",
)

load("@bzlmodrio-gentool-pip//:requirements.bzl", "install_deps")

install_deps()
