alias(
    name = "hal",
    actual = "@allwpilib//libraries/cpp/hal",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//libraries/cpp/hal:jni",
    visibility = ["//visibility:public"],
)
