alias(
    name = "hal",
    actual = "@allwpilib//dependencies/cpp/hal",
    visibility = ["//visibility:public"],
)
alias(
    name = "jni",
    actual = "@allwpilib//dependencies/cpp/hal",
    visibility = ["//visibility:public"],
)
