alias(
    name = "cameraserver",
    actual = "@allwpilib//dependencies/cpp/cameraserver",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//dependencies/cpp/jni",
    visibility = ["//visibility:public"],
)
