alias(
    name = "ntcore",
    actual = "@bzlmodrio-allwpilib//libraries/cpp/ntcore",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@bzlmodrio-allwpilib//libraries/cpp/ntcore:jni",
    visibility = ["//visibility:public"],
)
