alias(
    name = "ntcore",
    actual = "@allwpilib//dependencies/cpp/ntcore",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//dependencies/cpp/ntcore:jni",
    visibility = ["//visibility:public"],
)