java_library(
    name = "phoenix",
    visibility = ["//visibility:public"],
    exports = [
        "@bzlmodrio-phoenix//libraries/java/api-java",
        "@bzlmodrio-phoenix//libraries/java/wpiapi-java",
    ],
)
