alias(
    name = "cscore",
    actual = "@bzlmodrio-allwpilib//libraries/cpp/cscore",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@bzlmodrio-allwpilib//libraries/cpp/cscore:jni",
    visibility = ["//visibility:public"],
)
