alias(
    name = "cscore",
    actual = "@allwpilib//dependencies/cpp/cscore",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//dependencies/cpp/jni",
    visibility = ["//visibility:public"],
)