alias(
    name = "wpinet",
    actual = "@allwpilib//libraries/cpp/wpinet",
    visibility = ["//visibility:public"],
)

alias(
    name = "jni",
    actual = "@allwpilib//libraries/cpp/wpinet:jni",
    visibility = ["//visibility:public"],
)
