name: Build example project
on: [pull_request, push]
jobs:
  build_native:
    strategy:
      fail-fast: false
      matrix:
        include:
        # Build standard, native
        - { name: "windows - native",        os: windows-latest, command: "build",  config: "--config=windows", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - native",        os: ubuntu-latest,  command: "build",  config: "--config=linux",   bazel_options: "",                                 }
        - { name: "macos   - native",        os: macos-latest,   command: "build",  config: "--config=macos --test_tag_filters=-bazelrio-cpp-test",   bazel_options: "",                                 }

        # Build bzlmod, native
        - { name: "windows - bzlmod native", os: windows-latest, command: "build",  config: "--enable_bzlmod --config=windows", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - bzlmod native", os: ubuntu-latest,  command: "build",  config: "--enable_bzlmod --config=linux",   bazel_options: "",                                 }
        - { name: "macos   - bzlmod native", os: macos-latest,   command: "build",  config: "--enable_bzlmod --config=macos --test_tag_filters=-bazelrio-cpp-test",   bazel_options: "",                                 }

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: bazel ${{ matrix.bazel_options }} build -k ${{ matrix.config }} --verbose_failures --config=remote //... @bazelrio//...
      working-directory: tests
    - run: bazel ${{ matrix.bazel_options }} ${{ matrix.command }} //... -k ${{ matrix.config }} --verbose_failures --config=remote
      working-directory: tests

      
  build_roborio:
    strategy:
      fail-fast: false
      matrix:
        include:
        # Build standard, roborio
        - { name: "windows - cross",         os: windows-latest, command: "build", config: "--config=roborio", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - cross",         os: ubuntu-latest,  command: "build", config: "--config=roborio", bazel_options: "",                                 }
        - { name: "macos   - cross",         os: macos-latest,   command: "build", config: "--config=roborio", bazel_options: "",                                 }
        
        # Build bzlmod, roborio
      # - { name: "windows - bzlmod cross",  os: windows-latest, command: "build", config: "--enable_bzlmod --config=roborio", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - bzlmod cross",  os: ubuntu-latest,  command: "build", config: "--enable_bzlmod --config=roborio", bazel_options: "",                                 }
        - { name: "macos   - bzlmod cross",  os: macos-latest,   command: "build", config: "--enable_bzlmod --config=roborio", bazel_options: "",                                 }
    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: bazel ${{ matrix.bazel_options }} ${{ matrix.command }} //... -k ${{ matrix.config }} --verbose_failures --config=remote
      working-directory: tests