name: Publish Module
on:
  workflow_dispatch:
  push:
    tags:
    - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish_module:
    name: "Publish Module"
    runs-on: ubuntu-22.04
    steps:
    # Checkout repository
    - uses: actions/checkout@v4
      with:
        path: libraries/bzlmodrio

    - name: Create Archive
      run: git archive HEAD --format=tar.gz --output="bzlmodrio-${GITHUB_REF_NAME}.tar.gz"
      working-directory: libraries/bzlmodrio

    - name: Setup archive name
      run: echo "ARCHIVE_NAME=libraries/bzlmodrio/bzlmodrio-${GITHUB_REF_NAME}.tar.gz" >> "$GITHUB_ENV"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "${{ env.ARCHIVE_NAME }}"


    # Checkout bzlmodrio-opencv
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-opencv.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-opencv
        ref: main

    # Checkout bzlmodrio-ni
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-ni.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-ni
        ref: main

    # Checkout bzlmodrio-allwpilib
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-allwpilib.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-allwpilib
        ref: main

    # Checkout bzlmodrio-phoenix
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-phoenix.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-phoenix
        ref: main

    # Checkout bzlmodrio-phoenix6
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-phoenix6.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-phoenix6
        ref: main

    # Checkout bzlmodrio-revlib
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-revlib.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-revlib
        ref: main

    # Checkout bzlmodrio-navx
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-navx.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-navx
        ref: main

    # Checkout bzlmodrio-imgui
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-imgui.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-imgui
        ref: main

    # Checkout bzlmodrio-libssh
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-libssh.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-libssh
        ref: main

    # Checkout bzlmodrio-apriltaglib
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-apriltaglib.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-apriltaglib
        ref: main

    # Checkout bzlmodrio-pathplannerlib
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-pathplannerlib.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-pathplannerlib
        ref: main

    # Checkout bzlmodrio-photonlib
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bzlmodrio-photonlib.git'
        fetch-depth: 0
        path: libraries/bzlmodrio/../../libraries/bzlmodRio-photonlib
        ref: main




    # Checkout gentool
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/gentool.git'
        fetch-depth: 0
        path: gentool
        ref: refactor_dev

    # Checkout BCR
    - uses: actions/checkout@v4
      with:
        repository: 'bzlmodRio/bazel-central-registry.git'
        fetch-depth: 0
        path: bazel-central-registry
        ref: bzlmodrio

    # Run publishing
    - run: bazel run //:publish
      working-directory: libraries/bzlmodrio/generate

    - name: Store version
      run: echo "NEW_VERSION=$(bazel run //:get_version)" >> $GITHUB_ENV
      working-directory: libraries/bzlmodrio/generate


    # Create pull requests
    - name: Create Gentool Pull Request
      uses: peter-evans/create-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_KEY }}
      with:
        path: gentool
        base: refactor_dev
        token: ${{ secrets.AUTO_UPDATE_KEY }}
        branch: autoupdate/bzlmodrio_update_${{ env.NEW_VERSION }}
        title: "Auto Update bzlmodrio module to '${{ env.NEW_VERSION }}'"

    - name: Create BCR Pull Request
      uses: peter-evans/create-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_KEY }}
      with:
        path: bazel-central-registry
        base: bzlmodrio
        token: ${{ secrets.AUTO_UPDATE_KEY }}
        branch: autoupdate/bzlmodrio_update_${{ env.NEW_VERSION }}
        title: "Auto Update latest bzlmodrio to '${{ env.NEW_VERSION }}'"
